# Generated by Django 4.0.4 on 2022-12-21 06:10

import chat.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0005_alter_story_creator_alter_story_image'),
        ('users', '0003_resettable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=chat.models.message_path)),
                ('seen', models.BooleanField(default=False)),
                ('reaction_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reaction_to', models.CharField(blank=True, max_length=255, null=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bychat', related_query_name='bychat', to='users.profile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomessage', related_query_name='tomessage', to='users.profile')),
            ],
        ),
    ]
