version: '3.9'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: redis:6.2.4
  django:
    image: anuragravi/insta_backend:1.0.2
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db
      - redis
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      EMAIL_HOST_USER: teaminstaclone@gmail.com
      EMAIL_HOST_PASSWORD: khhfaesgiewpbcts
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - 80:80
    depends_on:
      - django