# Generated by Django 4.0.4 on 2022-07-10 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resettable'),
        ('feed', '0003_alter_post_image_story_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timedate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timedate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='posts', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timedate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='story',
            name='timedate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
