# Generated by Django 4.0.4 on 2022-11-06 14:05

from django.db import migrations, models
import django.db.models.deletion
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resettable'),
        ('feed', '0004_alter_activity_timedate_alter_comment_timedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_stories', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=feed.models.story_path),
        ),
    ]
